/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountPendingDeletionRouteImport } from './routes/account-pending-deletion'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminCommunitiesRouteImport } from './routes/admin/communities'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppDmRouteImport } from './routes/_app/dm'
import { Route as AppCommunityIdRouteRouteImport } from './routes/_app/$communityId/route'
import { Route as AppDmIndexRouteImport } from './routes/_app/dm/index'
import { Route as AppCommunityIdIndexRouteImport } from './routes/_app/$communityId/index'
import { Route as AppMMessageIdRouteImport } from './routes/_app/m/$messageId'
import { Route as AppInviteTokenRouteImport } from './routes/_app/invite/$token'
import { Route as AppDmNewRouteImport } from './routes/_app/dm/new'
import { Route as AppDmConversationIdRouteImport } from './routes/_app/dm/$conversationId'
import { Route as AppCommunityIdChannelIdRouteImport } from './routes/_app/$communityId/$channelId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPendingDeletionRoute = AccountPendingDeletionRouteImport.update({
  id: '/account-pending-deletion',
  path: '/account-pending-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesRoute = AdminCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppDmRoute = AppDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityIdRouteRoute = AppCommunityIdRouteRouteImport.update({
  id: '/$communityId',
  path: '/$communityId',
  getParentRoute: () => AppRoute,
} as any)
const AppDmIndexRoute = AppDmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDmRoute,
} as any)
const AppCommunityIdIndexRoute = AppCommunityIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCommunityIdRouteRoute,
} as any)
const AppMMessageIdRoute = AppMMessageIdRouteImport.update({
  id: '/m/$messageId',
  path: '/m/$messageId',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteTokenRoute = AppInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppDmNewRoute = AppDmNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDmRoute,
} as any)
const AppDmConversationIdRoute = AppDmConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AppDmRoute,
} as any)
const AppCommunityIdChannelIdRoute = AppCommunityIdChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => AppCommunityIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-pending-deletion': typeof AccountPendingDeletionRoute
  '/admin': typeof AdminRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/$communityId': typeof AppCommunityIdRouteRouteWithChildren
  '/dm': typeof AppDmRouteWithChildren
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/$communityId/$channelId': typeof AppCommunityIdChannelIdRoute
  '/dm/$conversationId': typeof AppDmConversationIdRoute
  '/dm/new': typeof AppDmNewRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/m/$messageId': typeof AppMMessageIdRoute
  '/$communityId/': typeof AppCommunityIdIndexRoute
  '/dm/': typeof AppDmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-pending-deletion': typeof AccountPendingDeletionRoute
  '/admin': typeof AdminRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/$communityId/$channelId': typeof AppCommunityIdChannelIdRoute
  '/dm/$conversationId': typeof AppDmConversationIdRoute
  '/dm/new': typeof AppDmNewRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/m/$messageId': typeof AppMMessageIdRoute
  '/$communityId': typeof AppCommunityIdIndexRoute
  '/dm': typeof AppDmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/account-pending-deletion': typeof AccountPendingDeletionRoute
  '/admin': typeof AdminRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_app/$communityId': typeof AppCommunityIdRouteRouteWithChildren
  '/_app/dm': typeof AppDmRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/_app/register': typeof AppRegisterRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/_app/$communityId/$channelId': typeof AppCommunityIdChannelIdRoute
  '/_app/dm/$conversationId': typeof AppDmConversationIdRoute
  '/_app/dm/new': typeof AppDmNewRoute
  '/_app/invite/$token': typeof AppInviteTokenRoute
  '/_app/m/$messageId': typeof AppMMessageIdRoute
  '/_app/$communityId/': typeof AppCommunityIdIndexRoute
  '/_app/dm/': typeof AppDmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-pending-deletion'
    | '/admin'
    | '/reset-password'
    | '/$communityId'
    | '/dm'
    | '/login'
    | '/register'
    | '/admin/audit'
    | '/admin/communities'
    | '/admin/health'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/$communityId/$channelId'
    | '/dm/$conversationId'
    | '/dm/new'
    | '/invite/$token'
    | '/m/$messageId'
    | '/$communityId/'
    | '/dm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-pending-deletion'
    | '/admin'
    | '/reset-password'
    | '/login'
    | '/register'
    | '/admin/audit'
    | '/admin/communities'
    | '/admin/health'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/$communityId/$channelId'
    | '/dm/$conversationId'
    | '/dm/new'
    | '/invite/$token'
    | '/m/$messageId'
    | '/$communityId'
    | '/dm'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/account-pending-deletion'
    | '/admin'
    | '/reset-password'
    | '/_app/$communityId'
    | '/_app/dm'
    | '/_app/login'
    | '/_app/register'
    | '/admin/audit'
    | '/admin/communities'
    | '/admin/health'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/_app/$communityId/$channelId'
    | '/_app/dm/$conversationId'
    | '/_app/dm/new'
    | '/_app/invite/$token'
    | '/_app/m/$messageId'
    | '/_app/$communityId/'
    | '/_app/dm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccountPendingDeletionRoute: typeof AccountPendingDeletionRoute
  AdminRoute: typeof AdminRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-pending-deletion': {
      id: '/account-pending-deletion'
      path: '/account-pending-deletion'
      fullPath: '/account-pending-deletion'
      preLoaderRoute: typeof AccountPendingDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities': {
      id: '/admin/communities'
      path: '/communities'
      fullPath: '/admin/communities'
      preLoaderRoute: typeof AdminCommunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dm': {
      id: '/_app/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof AppDmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$communityId': {
      id: '/_app/$communityId'
      path: '/$communityId'
      fullPath: '/$communityId'
      preLoaderRoute: typeof AppCommunityIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dm/': {
      id: '/_app/dm/'
      path: '/'
      fullPath: '/dm/'
      preLoaderRoute: typeof AppDmIndexRouteImport
      parentRoute: typeof AppDmRoute
    }
    '/_app/$communityId/': {
      id: '/_app/$communityId/'
      path: '/'
      fullPath: '/$communityId/'
      preLoaderRoute: typeof AppCommunityIdIndexRouteImport
      parentRoute: typeof AppCommunityIdRouteRoute
    }
    '/_app/m/$messageId': {
      id: '/_app/m/$messageId'
      path: '/m/$messageId'
      fullPath: '/m/$messageId'
      preLoaderRoute: typeof AppMMessageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite/$token': {
      id: '/_app/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AppInviteTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dm/new': {
      id: '/_app/dm/new'
      path: '/new'
      fullPath: '/dm/new'
      preLoaderRoute: typeof AppDmNewRouteImport
      parentRoute: typeof AppDmRoute
    }
    '/_app/dm/$conversationId': {
      id: '/_app/dm/$conversationId'
      path: '/$conversationId'
      fullPath: '/dm/$conversationId'
      preLoaderRoute: typeof AppDmConversationIdRouteImport
      parentRoute: typeof AppDmRoute
    }
    '/_app/$communityId/$channelId': {
      id: '/_app/$communityId/$channelId'
      path: '/$channelId'
      fullPath: '/$communityId/$channelId'
      preLoaderRoute: typeof AppCommunityIdChannelIdRouteImport
      parentRoute: typeof AppCommunityIdRouteRoute
    }
  }
}

interface AppCommunityIdRouteRouteChildren {
  AppCommunityIdChannelIdRoute: typeof AppCommunityIdChannelIdRoute
  AppCommunityIdIndexRoute: typeof AppCommunityIdIndexRoute
}

const AppCommunityIdRouteRouteChildren: AppCommunityIdRouteRouteChildren = {
  AppCommunityIdChannelIdRoute: AppCommunityIdChannelIdRoute,
  AppCommunityIdIndexRoute: AppCommunityIdIndexRoute,
}

const AppCommunityIdRouteRouteWithChildren =
  AppCommunityIdRouteRoute._addFileChildren(AppCommunityIdRouteRouteChildren)

interface AppDmRouteChildren {
  AppDmConversationIdRoute: typeof AppDmConversationIdRoute
  AppDmNewRoute: typeof AppDmNewRoute
  AppDmIndexRoute: typeof AppDmIndexRoute
}

const AppDmRouteChildren: AppDmRouteChildren = {
  AppDmConversationIdRoute: AppDmConversationIdRoute,
  AppDmNewRoute: AppDmNewRoute,
  AppDmIndexRoute: AppDmIndexRoute,
}

const AppDmRouteWithChildren = AppDmRoute._addFileChildren(AppDmRouteChildren)

interface AppRouteChildren {
  AppCommunityIdRouteRoute: typeof AppCommunityIdRouteRouteWithChildren
  AppDmRoute: typeof AppDmRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppInviteTokenRoute: typeof AppInviteTokenRoute
  AppMMessageIdRoute: typeof AppMMessageIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityIdRouteRoute: AppCommunityIdRouteRouteWithChildren,
  AppDmRoute: AppDmRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppInviteTokenRoute: AppInviteTokenRoute,
  AppMMessageIdRoute: AppMMessageIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCommunitiesRoute: typeof AdminCommunitiesRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCommunitiesRoute: AdminCommunitiesRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccountPendingDeletionRoute: AccountPendingDeletionRoute,
  AdminRoute: AdminRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
